### ISSUE TITLE
Fix publishing

### ISSUE THREAD

**Issue by walkah** [TFTInterchange/ToolsForThoughtLogSeq#3]
Get this repo publishing to GH pages.

**Comment by bmann** [comment]
OK, so I got the publish action publishing into the gh-pages branch, now I need the gh-pages branch to actually ... publish?

**Comment by walkah** [comment]
> OK, so I got the publish action publishing into the gh-pages branch, now I need the gh-pages branch to actually ... publish?

Looks like you did it! https://toolsforthoughtrocks.github.io/ToolsForThoughtLogSeq/

**Comment by bmann** [comment]
@walkah no, that's the old static one! the gh-pages branch has the right stuff in it ... but it's not, like, connected to actually being published.
